# Basic PCGR configuration options (TOML).

[tumor_only]
## Variant filtering applied for option --tumor_only = true in pcgr.py
## Several filters can be configured, all as a means to minimize the proportion of germline calls in the raw set derived from tumor-only calling

## Exclude variants (SNVs/InDels) with minor allele frequency above the following population-specific thresholds
## 1000 Genomes Project - WGS data
maf_onekg_eur = maf_onekg_eur_placeholder
maf_onekg_amr = maf_onekg_amr_placeholder
maf_onekg_afr = maf_onekg_afr_placeholder
maf_onekg_sas = maf_onekg_sas_placeholder
maf_onekg_eas = maf_onekg_eas_placeholder
maf_onekg_global = maf_onekg_global_placeholder

## exclude variants with minor allele frequency above the following population-specific thresholds
## gnomAD - WES data
maf_gnomad_nfe = maf_gnomad_nfe_placeholder
maf_gnomad_amr = maf_gnomad_amr_placeholder
maf_gnomad_afr = maf_gnomad_afr_placeholder
maf_gnomad_asj = maf_gnomad_asj_placeholder
maf_gnomad_sas = maf_gnomad_sas_placeholder
maf_gnomad_eas = maf_gnomad_eas_placeholder
maf_gnomad_fin = maf_gnomad_fin_placeholder
maf_gnomad_oth = maf_gnomad_oth_placeholder
maf_gnomad_global = maf_gnomad_global_placeholder

## Exclude variants occurring in PoN (panel of normals, if provided as VCF)
exclude_pon = exclude_pon_placeholder

## Exclude likely homozygous germline variants (100% allelic fraction for alternate allele in tumor, very unlikely somatic event)
exclude_likely_hom_germline = exclude_likely_hom_germline_placeholder

## Exclude likely heterozygous germline variants
## Must satisfy i) 40-60 % allelic fraction for alternate allele in tumor sample, ii) present in dbSNP + gnomAD, ii) not existing as somatic event in COSMIC/TCGA
## Note that the application of this filter may be suboptimal for very impure tumors or variants affected by CNAs etc (under these circumstances, the allelic fraction
## will be skewed (see e.g. discussion in PMID:29249243)
exclude_likely_het_germline = exclude_likely_het_germline_placeholder

## Exclude variants found in dbSNP (only those that are NOT found in ClinVar(somatic origin)/DoCM/TCGA/COSMIC)
exclude_dbsnp_nonsomatic = exclude_dbsnp_nonsomatic_placeholder

## exclude all non-exonic variants
exclude_nonexonic = exclude_nonexonic_placeholder

[allelic_support]
## Specify INFO tags in input VCF that denotes depth/allelic fraction in tumor and normal sample
## An additional tag that denotes call confidence (call_conf_tag) can also be specified, which will
## be used for exploration in the global variant browser. Note that 'tumor_dp_tag' must be of
## Type=Integer, and 'tumor_af_tag' must be of Type=Float (similarly for normal sample)
tumor_dp_tag = tumor_dp_tag_placeholder
tumor_af_tag = tumor_af_tag_placeholder
control_dp_tag = control_dp_tag_placeholder
control_af_tag = control_af_tag_placeholder
call_conf_tag = call_conf_tag_placeholder

[visual]
## Choose visual theme of report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = report_theme_placeholder

[custom_tags]
## list VCF info tags that should be present in JSON and TSV output
## tags should be comma separated, i.e. custom_tags = "MUTECT2_FILTER,STRELKA_FILTER"
custom_tags = custom_tags_placeholder

[other]
## list/do not list noncoding variants
list_noncoding = list_noncoding_placeholder
## VEP/vcfanno processing options
n_vcfanno_proc = n_vcfanno_proc_placeholder
n_vep_forks = n_vep_forks_placeholder
## Customise the order of criteria used to pick the primary transcript in VEP (see https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order)
vep_pick_order = vep_pick_order_placeholder
## omit intergenic variants during VEP processing
vep_skip_intergenic = vep_skip_intergenic_placeholder
## generate a MAF for input VCF using https://github.com/mskcc/vcf2maf
vcf2maf = vcf2maf_placeholder
